### ISSUE TITLE
I am sorry, just wanna ask. will this automatically update if i install trough install.sh that you provide ?

### ISSUE THREAD

**Issue by mumuhajir** [snwh/paper-gtk-theme#133]

**Comment by snwh** [comment]
Yes, it will prompt you to replace the existing installation.

**Comment by mumuhajir** [comment]
Will it update automatically when i update the system, or i have to redownload the file?

**Comment by snwh** [comment]
You will have to redownload. Unless you're using a package manager to get it.

**Comment by snwh** [comment]
```install.sh``` is just install. It doesn't upgrade or fetch files to update the theme.

**Comment by mumuhajir** [comment]
Okay.

**Comment by axel-sommerfeldt** [comment]
A way to ease the update process: Uninstall the paper theme, if installed. Do "git clone https://github.com/snwh/paper-gtk-theme.git" within a directory of your choice, e.g. ~/Downloads. Afterwards do "ln -s <your directory>/paper-gtk-theme/Paper ~/.local/share/themes". Now Paper is installed, and if you would like to update just do a "git pull" within the paper-gtk-theme directory (or as alternative do a "git pull <your directory>/paper-gtk-theme"). This way you can not just update the Paper theme with a single command, but it also saves bandwidth since "git pull" only pulls the differences (in a compressed format) and not the whole stuff.

**Comment by snwh** [comment]
This is true.

**Comment by mumuhajir** [comment]
Okay. 
Thanks. (By the way , Good Job). I love this theme.
