### ISSUE TITLE
Formatting Issues

### ISSUE THREAD

**Issue by dnlbaines** [snwh/paper-gtk-theme#356]
Since upgrading to Ubuntu 16.04 (Using Unity) I have been having formatting issues with the Paper theme. You can see the header of applications is now incorrectly separated and there is a dark blue highlight on selected/hovered items in menus as well. This happened briefly when I was on Ubuntu 15.10 but was then fixed and so appears to be a reoccuring issue:
![screenshot from 2016-05-19 16-07-29](https://cloud.githubusercontent.com/assets/3681102/15398561/fa6db024-1ddb-11e6-9b5c-8fdac190ff81.png)

**Comment by snwh** [comment]
The "formatting issue" is due to the header bar style in Paper having rounded corners and a highlight and it appear like that under Unity because the window manager conflicts with the headerbars in GTK and it draws the windows border instead of integrating the controls.

![screenshot from 2016-05-19 11-27-36](https://cloud.githubusercontent.com/assets/1217306/15399199/bb6285de-1db4-11e6-80bc-e3ad5ed39a37.png)

**Comment by dnlbaines** [comment]
Yes I understand that, however in the past this was not an issue so is there no possibility of having Unity specific behavior to remove this?

**Comment by snwh** [comment]
Ubuntu patches nautilus to use the Unity window manager. If you update Nautilus (say from the GNOME PPA) this issue goes away.

**Comment by dnlbaines** [comment]
Ah okay, I assume this is also case for other applications such as Gnome Software/Gedit then? Other than that the only issue that remains is that menu highlights are now a bright blue colour as opposed to a light grey (may be intentional?).

**Comment by snwh** [comment]
The blue is intentional.

**Comment by dnlbaines** [comment]
Okay thanks, my apologies!

**Comment by snwh** [comment]
No need to apologize. :smile:
